os: linux
dist: xenial
language: java
jdk:
- openjdk11

branches:
  only:
  - main
  - dev

addons:
  sonarcloud:
    organization: netcrackergroup2
    token: $SONARCLOUD_SECURED_TOKEN
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=NetCrackerGroup2_Cheetah-test

deploy:
  provider: heroku
  api_key: $HEROKU_SECURED_API_KEY
  app:
    main: cheetah-test-backend-prod
    dev: cheetah-test-backend-dev